import type { Ride, Booking, DepositTransaction, Review, City } from '../types'

// Demo rides data
export const demoRides: Ride[] = [
  {
    id: 'ride-001',
    driver_id: 'demo-user-001',
    origin: 'Ташкент',
    destination: 'Самарканд',
    intermediate_stops: ['Джизак'],
    departure_at: new Date(Date.now() + 86400000).toISOString(),
    price_per_seat: 120000,
    total_seats: 4,
    available_seats: 2,
    notes: 'Кондиционер, багаж OK',
    status: 'active',
    created_at: new Date().toISOString(),
    driver: {
      id: 'demo-user-001',
      role: 'driver',
      full_name: 'Алишер Каримов',
      phone: '+998901234567',
      avatar_url: null,
      car_model: 'Chevrolet Cobalt',
      car_color: 'Белый',
      license_plate: '01A123BC',
      seats_total: 4,
      deposit_balance: 500000,
      avg_rating: 4.5,
      rating_count: 12,
      language: 'ru',
      is_banned: false,
      created_at: '2024-01-15T10:00:00Z',
      updated_at: '2024-01-15T10:00:00Z',
    },
  },
  {
    id: 'ride-002',
    driver_id: 'demo-user-002',
    origin: 'Ташкент',
    destination: 'Бухара',
    intermediate_stops: ['Самарканд'],
    departure_at: new Date(Date.now() + 172800000).toISOString(),
    price_per_seat: 200000,
    total_seats: 3,
    available_seats: 3,
    notes: 'Не курю',
    status: 'active',
    created_at: new Date().toISOString(),
    driver: {
      id: 'demo-user-002',
      role: 'driver',
      full_name: 'Бахтиёр Рахимов',
      phone: '+998907654321',
      avatar_url: null,
      car_model: 'Chevrolet Gentra',
      car_color: 'Серый',
      license_plate: '40B456DE',
      seats_total: 3,
      deposit_balance: 300000,
      avg_rating: 4.8,
      rating_count: 25,
      language: 'ru',
      is_banned: false,
      created_at: '2024-02-10T10:00:00Z',
      updated_at: '2024-02-10T10:00:00Z',
    },
  },
  {
    id: 'ride-003',
    driver_id: 'demo-user-003',
    origin: 'Самарканд',
    destination: 'Фергана',
    intermediate_stops: null,
    departure_at: new Date(Date.now() + 43200000).toISOString(),
    price_per_seat: 150000,
    total_seats: 4,
    available_seats: 1,
    notes: null,
    status: 'active',
    created_at: new Date().toISOString(),
    driver: {
      id: 'demo-user-003',
      role: 'driver',
      full_name: 'Дильшод Умаров',
      phone: '+998911112233',
      avatar_url: null,
      car_model: 'Lacetti',
      car_color: 'Чёрный',
      license_plate: '30C789FG',
      seats_total: 4,
      deposit_balance: 150000,
      avg_rating: 3.9,
      rating_count: 7,
      language: 'ru',
      is_banned: false,
      created_at: '2024-03-01T10:00:00Z',
      updated_at: '2024-03-01T10:00:00Z',
    },
  },
  {
    id: 'ride-004',
    driver_id: 'demo-user-001',
    origin: 'Бухара',
    destination: 'Ташкент',
    intermediate_stops: ['Навои', 'Джизак'],
    departure_at: new Date(Date.now() + 259200000).toISOString(),
    price_per_seat: 180000,
    total_seats: 4,
    available_seats: 4,
    notes: 'Багаж OK, кондиционер',
    status: 'active',
    created_at: new Date().toISOString(),
    driver: {
      id: 'demo-user-001',
      role: 'driver',
      full_name: 'Алишер Каримов',
      phone: '+998901234567',
      avatar_url: null,
      car_model: 'Chevrolet Cobalt',
      car_color: 'Белый',
      license_plate: '01A123BC',
      seats_total: 4,
      deposit_balance: 500000,
      avg_rating: 4.5,
      rating_count: 12,
      language: 'ru',
      is_banned: false,
      created_at: '2024-01-15T10:00:00Z',
      updated_at: '2024-01-15T10:00:00Z',
    },
  },
  {
    id: 'ride-005',
    driver_id: 'demo-user-002',
    origin: 'Наманган',
    destination: 'Ташкент',
    intermediate_stops: null,
    departure_at: new Date(Date.now() + 108000000).toISOString(),
    price_per_seat: 130000,
    total_seats: 3,
    available_seats: 2,
    notes: 'Выезд рано утром',
    status: 'active',
    created_at: new Date().toISOString(),
    driver: {
      id: 'demo-user-002',
      role: 'driver',
      full_name: 'Бахтиёр Рахимов',
      phone: '+998907654321',
      avatar_url: null,
      car_model: 'Chevrolet Gentra',
      car_color: 'Серый',
      license_plate: '40B456DE',
      seats_total: 3,
      deposit_balance: 300000,
      avg_rating: 4.8,
      rating_count: 25,
      language: 'ru',
      is_banned: false,
      created_at: '2024-02-10T10:00:00Z',
      updated_at: '2024-02-10T10:00:00Z',
    },
  },
  {
    id: 'ride-006',
    driver_id: 'demo-user-003',
    origin: 'Ташкент',
    destination: 'Нукус',
    intermediate_stops: ['Бухара', 'Ургенч'],
    departure_at: new Date(Date.now() + 345600000).toISOString(),
    price_per_seat: 350000,
    total_seats: 4,
    available_seats: 3,
    notes: 'Долгая поездка, перерывы в пути',
    status: 'active',
    created_at: new Date().toISOString(),
    driver: {
      id: 'demo-user-003',
      role: 'driver',
      full_name: 'Дильшод Умаров',
      phone: '+998911112233',
      avatar_url: null,
      car_model: 'Lacetti',
      car_color: 'Чёрный',
      license_plate: '30C789FG',
      seats_total: 4,
      deposit_balance: 150000,
      avg_rating: 3.9,
      rating_count: 7,
      language: 'ru',
      is_banned: false,
      created_at: '2024-03-01T10:00:00Z',
      updated_at: '2024-03-01T10:00:00Z',
    },
  },
]

export const demoBookings: Booking[] = [
  {
    id: 'booking-001',
    ride_id: 'ride-001',
    passenger_id: 'demo-user-001',
    status: 'confirmed',
    commission_amount: 12000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ride: demoRides[0],
    passenger: {
      id: 'demo-passenger-001',
      role: 'passenger',
      full_name: 'Нодира Ахмедова',
      phone: '+998901111111',
      avatar_url: null,
      car_model: null,
      car_color: null,
      license_plate: null,
      seats_total: null,
      deposit_balance: 0,
      avg_rating: 4.2,
      rating_count: 5,
      language: 'ru',
      is_banned: false,
      created_at: '2024-01-20T10:00:00Z',
      updated_at: '2024-01-20T10:00:00Z',
    },
  },
  {
    id: 'booking-002',
    ride_id: 'ride-002',
    passenger_id: 'demo-user-001',
    status: 'pending',
    commission_amount: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ride: demoRides[1],
  },
]

export const demoTransactions: DepositTransaction[] = [
  {
    id: 'tx-001',
    driver_id: 'demo-user-001',
    type: 'top_up',
    amount: 500000,
    balance_after: 500000,
    booking_id: null,
    note: 'Initial deposit',
    created_by: null,
    created_at: '2024-01-15T12:00:00Z',
  },
  {
    id: 'tx-002',
    driver_id: 'demo-user-001',
    type: 'commission',
    amount: -12000,
    balance_after: 488000,
    booking_id: 'booking-001',
    note: 'Commission for booking confirmation',
    created_by: null,
    created_at: '2024-01-20T14:00:00Z',
  },
  {
    id: 'tx-003',
    driver_id: 'demo-user-001',
    type: 'commission',
    amount: -15000,
    balance_after: 473000,
    booking_id: null,
    note: 'Commission for booking confirmation',
    created_by: null,
    created_at: '2024-02-05T09:00:00Z',
  },
  {
    id: 'tx-004',
    driver_id: 'demo-user-001',
    type: 'top_up',
    amount: 200000,
    balance_after: 673000,
    booking_id: null,
    note: 'Top-up via admin',
    created_by: null,
    created_at: '2024-02-15T11:00:00Z',
  },
]

export const demoReviews: Review[] = [
  {
    id: 'review-001',
    booking_id: 'booking-001',
    reviewer_id: 'demo-passenger-001',
    reviewee_id: 'demo-user-001',
    rating: 5,
    comment: 'Отличный водитель! Доехали быстро и комфортно.',
    created_at: '2024-01-22T10:00:00Z',
    reviewer: {
      id: 'demo-passenger-001',
      role: 'passenger',
      full_name: 'Нодира Ахмедова',
      phone: '+998901111111',
      avatar_url: null,
      car_model: null, car_color: null, license_plate: null, seats_total: null,
      deposit_balance: 0, avg_rating: 4.2, rating_count: 5,
      language: 'ru', is_banned: false,
      created_at: '2024-01-20T10:00:00Z', updated_at: '2024-01-20T10:00:00Z',
    },
  },
  {
    id: 'review-002',
    booking_id: 'booking-001',
    reviewer_id: 'demo-passenger-002',
    reviewee_id: 'demo-user-001',
    rating: 4,
    comment: 'Хорошая поездка, вовремя.',
    created_at: '2024-02-10T10:00:00Z',
    reviewer: {
      id: 'demo-passenger-002',
      role: 'passenger',
      full_name: 'Фарход Исмаилов',
      phone: '+998902222222',
      avatar_url: null,
      car_model: null, car_color: null, license_plate: null, seats_total: null,
      deposit_balance: 0, avg_rating: 0, rating_count: 0,
      language: 'ru', is_banned: false,
      created_at: '2024-02-01T10:00:00Z', updated_at: '2024-02-01T10:00:00Z',
    },
  },
]

export const demoCities: City[] = [
  { id: 1, name_ru: 'Ташкент', name_uz: 'Toshkent', region_ru: 'Ташкентская область', region_uz: 'Toshkent viloyati' },
  { id: 2, name_ru: 'Самарканд', name_uz: 'Samarqand', region_ru: 'Самаркандская область', region_uz: 'Samarqand viloyati' },
  { id: 3, name_ru: 'Бухара', name_uz: 'Buxoro', region_ru: 'Бухарская область', region_uz: 'Buxoro viloyati' },
  { id: 4, name_ru: 'Наманган', name_uz: 'Namangan', region_ru: 'Наманганская область', region_uz: 'Namangan viloyati' },
  { id: 5, name_ru: 'Андижан', name_uz: 'Andijon', region_ru: 'Андижанская область', region_uz: 'Andijon viloyati' },
  { id: 6, name_ru: 'Фергана', name_uz: "Farg'ona", region_ru: 'Ферганская область', region_uz: "Farg'ona viloyati" },
  { id: 7, name_ru: 'Нукус', name_uz: 'Nukus', region_ru: 'Каракалпакстан', region_uz: "Qoraqalpog'iston" },
  { id: 8, name_ru: 'Карши', name_uz: 'Qarshi', region_ru: 'Кашкадарьинская область', region_uz: 'Qashqadaryo viloyati' },
  { id: 9, name_ru: 'Навои', name_uz: 'Navoiy', region_ru: 'Навоийская область', region_uz: 'Navoiy viloyati' },
  { id: 10, name_ru: 'Термез', name_uz: 'Termiz', region_ru: 'Сурхандарьинская область', region_uz: 'Surxondaryo viloyati' },
  { id: 11, name_ru: 'Джизак', name_uz: 'Jizzax', region_ru: 'Джизакская область', region_uz: 'Jizzax viloyati' },
  { id: 12, name_ru: 'Ургенч', name_uz: 'Urganch', region_ru: 'Хорезмская область', region_uz: 'Xorazm viloyati' },
  { id: 13, name_ru: 'Коканд', name_uz: "Qo'qon", region_ru: 'Ферганская область', region_uz: "Farg'ona viloyati" },
  { id: 14, name_ru: 'Чирчик', name_uz: 'Chirchiq', region_ru: 'Ташкентская область', region_uz: 'Toshkent viloyati' },
  { id: 15, name_ru: 'Хива', name_uz: 'Xiva', region_ru: 'Хорезмская область', region_uz: 'Xorazm viloyati' },
]
