services:
  # Web service - your FastAPI application
  - type: web
    name: autoport-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      # Database connection - will be auto-populated by Render
      - key: DATABASE_URL
        fromDatabase:
          name: autoport-db
          property: connectionString
      
      # JWT configuration - CHANGE THESE IN PRODUCTION!
      - key: JWT_SECRET_KEY
        generateValue: true  # Render will generate a secure random value
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      
      # Application settings
      - key: APP_NAME
        value: AutoPort API
      - key: APP_VERSION
        value: 0.1.0
      - key: ENVIRONMENT
        value: production

databases:
  # PostgreSQL database
  - name: autoport-db
    plan: free  # or 'starter' for production
    postgresMajorVersion: 15