-- Seed Uzbekistan cities
INSERT INTO cities (name_ru, name_uz, region_ru, region_uz) VALUES
  ('Ташкент', 'Toshkent', 'Ташкентская область', 'Toshkent viloyati'),
  ('Самарканд', 'Samarqand', 'Самаркандская область', 'Samarqand viloyati'),
  ('Бухара', 'Buxoro', 'Бухарская область', 'Buxoro viloyati'),
  ('Наманган', 'Namangan', 'Наманганская область', 'Namangan viloyati'),
  ('Андижан', 'Andijon', 'Андижанская область', 'Andijon viloyati'),
  ('Фергана', 'Farg''ona', 'Ферганская область', 'Farg''ona viloyati'),
  ('Нукус', 'Nukus', 'Каракалпакстан', 'Qoraqalpog''iston'),
  ('Карши', 'Qarshi', 'Кашкадарьинская область', 'Qashqadaryo viloyati'),
  ('Навои', 'Navoiy', 'Навоийская область', 'Navoiy viloyati'),
  ('Термез', 'Termiz', 'Сурхандарьинская область', 'Surxondaryo viloyati'),
  ('Джизак', 'Jizzax', 'Джизакская область', 'Jizzax viloyati'),
  ('Ургенч', 'Urganch', 'Хорезмская область', 'Xorazm viloyati'),
  ('Коканд', 'Qo''qon', 'Ферганская область', 'Farg''ona viloyati'),
  ('Маргилан', 'Marg''ilon', 'Ферганская область', 'Farg''ona viloyati'),
  ('Чирчик', 'Chirchiq', 'Ташкентская область', 'Toshkent viloyati'),
  ('Алмалык', 'Olmaliq', 'Ташкентская область', 'Toshkent viloyati'),
  ('Ангрен', 'Angren', 'Ташкентская область', 'Toshkent viloyati'),
  ('Гулистан', 'Guliston', 'Сырдарьинская область', 'Sirdaryo viloyati'),
  ('Денау', 'Denov', 'Сурхандарьинская область', 'Surxondaryo viloyati'),
  ('Шахрисабз', 'Shahrisabz', 'Кашкадарьинская область', 'Qashqadaryo viloyati'),
  ('Зарафшан', 'Zarafshon', 'Навоийская область', 'Navoiy viloyati'),
  ('Бекабад', 'Bekobod', 'Ташкентская область', 'Toshkent viloyati'),
  ('Хива', 'Xiva', 'Хорезмская область', 'Xorazm viloyati'),
  ('Каган', 'Kogon', 'Бухарская область', 'Buxoro viloyati'),
  ('Турткуль', 'To''rtko''l', 'Каракалпакстан', 'Qoraqalpog''iston'),
  ('Кунград', 'Qo''ng''irot', 'Каракалпакстан', 'Qoraqalpog''iston'),
  ('Муйнак', 'Mo''ynoq', 'Каракалпакстан', 'Qoraqalpog''iston'),
  ('Нурафшон', 'Nurafshon', 'Ташкентская область', 'Toshkent viloyati'),
  ('Янгиюль', 'Yangiyo''l', 'Ташкентская область', 'Toshkent viloyati'),
  ('Газалкент', 'G''azalkent', 'Ташкентская область', 'Toshkent viloyati'),
  ('Ахангаран', 'Ohangaron', 'Ташкентская область', 'Toshkent viloyati'),
  ('Кибрай', 'Kibray', 'Ташкентская область', 'Toshkent viloyati'),
  ('Учкудук', 'Uchquduq', 'Навоийская область', 'Navoiy viloyati'),
  ('Каттакурган', 'Kattaqo''rg''on', 'Самаркандская область', 'Samarqand viloyati'),
  ('Ургут', 'Urgut', 'Самаркандская область', 'Samarqand viloyati'),
  ('Китаб', 'Kitob', 'Кашкадарьинская область', 'Qashqadaryo viloyati'),
  ('Гиждуван', 'G''ijduvon', 'Бухарская область', 'Buxoro viloyati'),
  ('Газли', 'Gazli', 'Бухарская область', 'Buxoro viloyati'),
  ('Шуртан', 'Sho''rtan', 'Кашкадарьинская область', 'Qashqadaryo viloyati'),
  ('Асака', 'Asaka', 'Андижанская область', 'Andijon viloyati'),
  ('Пап', 'Pop', 'Наманганская область', 'Namangan viloyati'),
  ('Чуст', 'Chust', 'Наманганская область', 'Namangan viloyati'),
  ('Кувасай', 'Quvasoy', 'Ферганская область', 'Farg''ona viloyati'),
  ('Риштан', 'Rishton', 'Ферганская область', 'Farg''ona viloyati'),
  ('Шахрихан', 'Shahrixon', 'Андижанская область', 'Andijon viloyati'),
  ('Яккабаг', 'Yakkabog''', 'Кашкадарьинская область', 'Qashqadaryo viloyati'),
  ('Байсун', 'Boysun', 'Сурхандарьинская область', 'Surxondaryo viloyati'),
  ('Шерабад', 'Sherobod', 'Сурхандарьинская область', 'Surxondaryo viloyati'),
  ('Кумкурган', 'Qumqo''rg''on', 'Сурхандарьинская область', 'Surxondaryo viloyati'),
  ('Косонсой', 'Kosonsoy', 'Наманганская область', 'Namangan viloyati');
